# Generated by Django 2.1.4 on 2019-01-05 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 15, 2, 31, 991395)),
        ),
    ]
