# Generated by Django 2.1.4 on 2018-12-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_aa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='aa',
        ),
    ]
